export type ParticleReactTarget = "peel" | "size" | "diffusion" | "noise" | "hue";

export type ParticleTuning = {
  particleCount: number;
  particleSize: number;
  trailLength: number;
  contrast: number;
  flowSpeed: number;
  flowAmplitude: number;
  depthStrength: number;
  depthWave: number;
  coreRetention: number;
  haloWidth: number;
  haloDensity: number;
  edgeFeather: number;
  clusterIrregularity: number;
  densityGamma: number;
  sparkleAmount: number;
  homeSpring: number;
  velocityDamping: number;
  mouseRadius: number;
  mouseForce: number;
  mouseRepulsion: number;
  mouseSwirl: number;
  mouseRingWidth: number;
  mouseDepthPull: number;
  pointerSmoothing: number;
  colorShiftSpeed: number;
  danceStrength: number;
  audioBrightnessStrength: number;
  audioBloomStrength: number;
  bassGain: number;
  flowReactStrength: number;
  depthReactStrength: number;
  sparkleReactStrength: number;
  audioNoiseGate: number;
  audioDynamicCurve: number;
  audioAttack: number;
  audioRelease: number;
  highlightGain: number;
  bloomStrength: number;
  bloomRadius: number;
  bloomThreshold: number;
  diffusion: number;
  noiseStrength: number;
  noiseFrequency: number;
  peelThreshold: number;
  erosionRate: number;
  windX: number;
  windY: number;
  emberLifespan: number;
  edgePerturbation: number;
  edgeScatter: number;
  hueDrift: number;
  luminanceMultiplier: number;
  rhythmIntensity: number;
  reactTarget: ParticleReactTarget;
  audioSmoothing: number;
};

export const DEFAULT_PARTICLE_TUNING: ParticleTuning = {
  particleCount: 262_144,
  particleSize: 2.8,
  trailLength: 0.76,
  contrast: 1.3,
  flowSpeed: 1,
  flowAmplitude: 1.15,
  depthStrength: 50,
  depthWave: 5,
  coreRetention: 0.93,
  haloWidth: 0.34,
  haloDensity: 0.52,
  edgeFeather: 0.27,
  clusterIrregularity: 0.42,
  densityGamma: 0.75,
  sparkleAmount: 0.12,
  homeSpring: 0.068,
  velocityDamping: 0.94,
  mouseRadius: 110,
  mouseForce: 1.15,
  mouseRepulsion: 0.28,
  mouseSwirl: 0.5,
  mouseRingWidth: 0.18,
  mouseDepthPull: 0.95,
  pointerSmoothing: 0.16,
  colorShiftSpeed: 2,
  danceStrength: 8.4,
  audioBrightnessStrength: 0.7,
  audioBloomStrength: 0.68,
  bassGain: 1.7,
  flowReactStrength: 0.9,
  depthReactStrength: 0.85,
  sparkleReactStrength: 0.46,
  audioNoiseGate: 0.06,
  audioDynamicCurve: 0.72,
  audioAttack: 0.025,
  audioRelease: 0.2,
  highlightGain: 1.8,
  bloomStrength: 1.15,
  bloomRadius: 0.55,
  bloomThreshold: 0.58,
  diffusion: 1.6,
  noiseStrength: 1.25,
  noiseFrequency: 1.1,
  peelThreshold: 0.6,
  erosionRate: 0.12,
  windX: 0.05,
  windY: 0.075,
  emberLifespan: 6.5,
  edgePerturbation: 1.1,
  edgeScatter: 6.8,
  hueDrift: 16,
  luminanceMultiplier: 1.8,
  rhythmIntensity: 2.8,
  reactTarget: "peel",
  audioSmoothing: 0.78,
};
